apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
  name: fluentd-prometheus-conf
data:
  prometheus.conf: |-
      <source>
        @type prometheus
        @id in_prometheus
        bind "kube-prometheus-stack-kube-state-metrics"
        port 8080
        metrics_path "/metrics"
      </source>

      <source>
        @type prometheus_monitor
        @id in_prometheus_monitor
      </source>

      <source>
        @type prometheus_output_monitor
        @id in_prometheus_output_monitor
      </source>